SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE COTACAO (
	IDCOTACAO INT NOT NULL AUTO_INCREMENT
    , DTCOTACAO DATE
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY (IDCOTACAO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , IDPRODUTO INT NOT NULL
    , DTVENDA DATE
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , PRIMARY KEY (IDVENDA)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
    );


DELIMITER $$

CREATE TRIGGER TR_VENDA_B_I BEFORE INSERT ON VENDA FOR EACH ROW
BEGIN
	-- DECLARANDO AS VARIAVEIS
	DECLARE vVALOR NUMERIC(8,2);
    DECLARE vDOLAR NUMERIC(8,2);
    DECLARE vQTDE_COTACAO INT;
    
    -- BUSCANDO A QUANTIDADE DE COTAÇÃO PARA A DATA INFORMADA
    SELECT	COUNT(IDCOTACAO)
    INTO 	vQTDE_COTACAO
    FROM	COTACAO
    WHERE	DTCOTACAO = NEW.DTVENDA;
    
    -- VERIFICANDO SE EXISTE APENAS 1 COTAÇÃO PARA A DATA INFORMADA
    IF(vQTDE_COTACAO = 1) THEN
		
		-- BUSCANDO O VALOR DO PRODUTO NA TABELA DE PRODUTOS
		SELECT	VALOR
		INTO 	vVALOR
		FROM	PRODUTO
		WHERE	IDPRODUTO = NEW.IDPRODUTO;
		
		-- BUSCANDO A COTAÇÃO DO DOLAR PARA A DATA DA VENDA
		SELECT	VALOR
		INTO 	vDOLAR
		FROM 	COTACAO
		WHERE	DTCOTACAO = NEW.DTVENDA;
		
		-- ATUALIZANDO O VALOR EM REAL DO PRODUTO, PARA QUE FIQUE O VALOR DEFINIDO NA TABELA PODUTO
		SET NEW.VALOR_REAL = vVALOR;
        SET NEW.VALOR_DOLAR= vVALOR / vDOLAR;
	ELSE
		SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Não existe uma unica cotação para a data informada';
    END IF;

END $$

CREATE TRIGGER TR_VENDA_B_U BEFORE UPDATE ON VENDA FOR EACH ROW
BEGIN

	-- DECLARANDO AS VARIAVEIS
	DECLARE vVALOR NUMERIC(8,2);
    DECLARE vDOLAR NUMERIC(8,2);
    DECLARE vQTDE_COTACAO INT;
    
    -- BUSCANDO A QUANTIDADE DE COTAÇÃO PARA A DATA INFORMADA
    SELECT	COUNT(IDCOTACAO)
    INTO 	vQTDE_COTACAO
    FROM	COTACAO
    WHERE	DTCOTACAO = NEW.DTVENDA;

    -- VERIFICANDO SE EXISTE ALGO DIFERENTE DE 1 COTAÇÃO PARA A DATA INFORMADA
    IF(vQTDE_COTACAO <> 1) THEN
		SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Não existe uma unica cotação para a data informada';
    ELSE 

		-- VERIFICANDO SE O PRODUTO FOI ALTERADO OU A DATA DA VENDA
		IF	(NEW.IDPRODUTO <> OLD.IDPRODUTO)
			OR (NEW.DTVENDA <> OLD.DTVENDA) THEN            

			-- BUSCANDO O VALOR DO PRODUTO NA TABELA DE PRODUTOS
			SELECT	VALOR
			INTO 	vVALOR
			FROM	PRODUTO
			WHERE	IDPRODUTO = NEW.IDPRODUTO;
		
			-- BUSCANDO A COTAÇÃO DO DOLAR PARA A DATA DA VENDA
			SELECT	VALOR
			INTO 	vDOLAR
			FROM 	COTACAO
			WHERE	DTCOTACAO = NEW.DTVENDA;            
            
			SET NEW.VALOR_REAL = vVALOR;            
			SET NEW.VALOR_DOLAR = vVALOR / vDOLAR;
            
		-- VERIFICANDO SE O PRODUTO E A DATA DA VENDA É O MESMO E O VALOR É DIFERENTE
		ELSEIF	((NEW.IDPRODUTO = OLD.IDPRODUTO)AND(NEW.DTVENDA = OLD.DTVENDA))
				AND ((NEW.VALOR_REAL <> OLD.VALOR_REAL) OR (NEW.VALOR_DOLAR <> OLD.VALOR_DOLAR)) THEN
                
			-- VOLTANDO O VALOR ANTERIO ANTES DA ALTERAÇÃO
			SET NEW.VALOR_REAL = OLD.VALOR_REAL;            
			SET NEW.VALOR_DOLAR = OLD.VALOR_DOLAR;
                
		END IF;

    END IF;
	
END $$

DELIMITER ;




INSERT INTO PRODUTO (NOME, VALOR)VALUES('CELULAR', 200);
INSERT INTO PRODUTO (NOME, VALOR)VALUES('TABLET', 350);

INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -5 DAY)), 4.09 - 0.55);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -4 DAY)), 4.09 - 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -3 DAY)), 4.09 - 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -2 DAY)), 4.09 - 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -1 DAY)), 4.09 - 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  0 DAY)), 4.09 - 0.05);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  1 DAY)), 4.09 + 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  2 DAY)), 4.09 + 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  3 DAY)), 4.09 + 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  4 DAY)), 4.09 + 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  5 DAY)), 4.09 + 0.55);

INSERT INTO VENDA (IDPRODUTO, DTVENDA, VALOR_REAL)
VALUES (1, '2023-10-28', 10);

SELECT * FROM COTACAO WHERE DTCOTACAO = '2023-10-28';
SELECT * FROM PRODUTO;
SELECT * FROM VENDA;


/*
QUESTÃO:
1. UTILIZE O VALOR DA TABELA DE PRODUTO SEMPRE QUE UM PRODUTO FOR INCLUIDO OU ALTERADO

2. SÓ PODE INCLUIR VENDA, SE TIVER COTAÇÃO PARA A DATA DA VENDA

3. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR CALCULADO COM BASE NA COTAÇÃO, PARA LOCALIZAR A COTAÇÃO 
COMPARE A DATA DE VENDA COM A DATA DA COTACAO;

*/

UPDATE VENDA SET IDPRODUTO = 1 WHERE IDVENDA = 1;
UPDATE VENDA SET IDPRODUTO = 2 WHERE IDVENDA = 1;
UPDATE VENDA SET DTVENDA = '2023-10-27' WHERE IDVENDA = 1;
UPDATE VENDA SET DTVENDA = '2023-10-28' WHERE IDVENDA = 1;
UPDATE VENDA SET VALOR_REAL = 10 WHERE IDVENDA = 1;
UPDATE VENDA SET VALOR_DOLAR = 10 WHERE IDVENDA = 1;
UPDATE VENDA SET VALOR_REAL = 10, DTVENDA = '2023-10-26' WHERE IDVENDA = 1;
SELECT * FROM VENDA;
